config/routes.rb
Rails.application.routes.draw do
  root 'sequoia#show'

  get '/sequoia_number', to: 'sequoia#show',
                         as: :sequoia_number

  get '/sequoia_number/search', to: 'sequoia#search',
                                as: :search_sequoia_number
  get '/sequoia_number/auto_complete', to: 'sequoia#auto_complete',
                                       as: :search_auto_complete

  get '/about', to: 'statics#about',
                as: :about

  get '/investment/nasdaq', to: 'investment#show_nasdaq',
                            as: :nasdaq_analysis
  get '/investment/unemployment', to: 'investment#show_unemployment',
                            as: :unemployment_analysis
end

app/models/company.rb
class Company < ActiveRecord::Base
  include AttributesMixin
  include NodeMixin
  include CrunchbaseMixin
end

app/models/concerns/attributes_mixin.rb
module AttributesMixin
  extend ActiveSupport::Concern

  def update_attributes_if_nil!(attributes)
    attributes.each do |k, v|
      self.send("#{k}=", v) unless self.send("#{k}")
    end

    self.save!
  end
end

app/models/concerns/crunchbase_mixin.rb
module CrunchbaseMixin
  extend ActiveSupport::Concern

  def crunchbase_link
    "http://www.crunchbase.com#{permalink}"
  end
end

app/models/concerns/node_mixin.rb
module NodeMixin
  extend ActiveSupport::Concern

  included do
    after_create :create_node
  end

  def create_node
    my_node = Neography::Node.create({"name" => name}, $neo)
    $neo.set_label(my_node, label)

    update_attribute :neo_id, my_node.neo_id.to_i
  end

  def label
    self.class.to_s
  end

  def node
    @node ||= Neography::Node.load neo_id, $neo
  end
end

app/models/investing.rb
class Investing < ActiveRecord::Base
  belongs_to :company
  belongs_to :investor

  after_create :create_relationship

  def amount=(num)
    num.gsub!(',','') if num.is_a?(String)
    self[:amount] = num.to_i
  end

  def create_relationship
    r1 = Neography::Relationship.create(:investment,
                                        company.node, investor.node)
    r2 = Neography::Relationship.create(:investment,
                                        investor.node, company.node)
    update_attribute :neo_id, r1.neo_id.to_i
  end
end

app/models/investor.rb
class Investor < ActiveRecord::Base
  include AttributesMixin
  include NodeMixin
  include CrunchbaseMixin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/investment_controller.rb
class InvestmentController < ApplicationController
  def show_nasdaq
  end

  def show_unemployment
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def sequoia_number
  end

  def search_sequoia_number
    @source = params[:source]
    @target = params[:target]

    unless !@source.try(:empty?) && !@target.try(:empty?)
      return render json: {error: 'Please specify both source and target!'}
    end

    @path = ShortestPathFinder.new(@source, @target).find

    if @path
      render json: @path
    else
      render json: {error: "No path find between #{@source} and #{@target}!"}
    end
  end
end

app/controllers/sequoia_controller.rb
class SequoiaController < ApplicationController
  def show
  end

  def search
    @source = params[:source]
    @target = params[:target]

    unless !@source.try(:empty?) && !@target.try(:empty?)
      return render json: {error: 'Please specify both source and target!'}
    end

    @path = ShortestPathFinder.new(@source, @target).find

    logger.debug { "Search path:" }
    logger.debug { @path.inspect }

    if @path
      render json: @path
    else
      render json: {error: "No path find between #{@source} and #{@target}!"}
    end
  end

  def auto_complete
    term = params['term']
    results = Investor.where(Investor.arel_table[:name].matches("%#{term}%"))
                      .order(name: :asc).limit(15).pluck(:name)

    logger.debug { "Auto Complete:" }
    logger.debug { results }

    render json: results
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investment_helper.rb
module InvestmentHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
  def crunch_base_link(node)
     "http://www.crunchbase.com#{node.permalink}"
  end

  def target_value(value)
    unless value.try :empty?
      value
    else
      'Sequoia Capital'
    end
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/investment/show_nasdaq.html.erb
<div id='investment'>
  <div id='investment-title'>
    NASDAQ Indices <span id='vs'>VS</span> Tech Company Investment Amount
  </div>
  <div id='investment-graph'></div>
  <script>
    var margin = {top: 30, right: 60, bottom: 30, left: 60},
        width = 950 - margin.left - margin.right,
        height = 500 - margin.top - margin.bottom;

    var x = d3.time.scale()
        .range([0, width-63]);
    var y = d3.scale.linear()
        .range([height, 0]);

    var x2 = d3.scale.ordinal()
        .rangeBands([0, width-63], .1);
    var y2 = d3.scale.linear()
        .range([height, 0]);

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom");
    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left");

    var x2Axis = d3.svg.axis()
        .scale(x)
        .orient("top");
    var yAxisRight = d3.svg.axis()
        .scale(y2)
        .orient("right")


    var line = d3.svg.line()
        .x(function(d) { return x(d.date); })
        .y(function(d) { return y(d.valueAtClose); });

    var svg = d3.select("#investment-graph").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    //bar graph for amount
    d3.tsv("/data/date_investmentAmount.tsv", type, function(error, data) {
      x2.domain(data.map(function(d) {
        return d.date; }));
      y2.domain([0, d3.max(data, function(d) {
        return parseFloat(d.amount); })]);


      svg.append("g")
          .attr("class", "y axis axisRight")
          .attr("transform", "translate(" + (width-62) + ","+(0)+")")
          .call(yAxisRight)
          .append("text")
          .attr("transform", "translate("+(110)+","+(-20)+")")
          .attr("y", 0)
          .attr("dy", ".71em")
          .style("text-anchor", "end")
          .text("Investment ($)");

      svg.selectAll(".bar")
          .data(data)
          .enter().append("rect")
          .attr("class", "bar")
          .attr("x", function(d) { return x2(d.date); })
          .attr("width", x2.rangeBand())
          .attr("y", function(d) { return y2(d.amount); })
          .attr("height", function(d) {
            return (height - y2(d.amount)); }
          );
    });

    // line graph for nasdaq index.
    d3.tsv("/data/nasdaq_indice.tsv", function(error, data) {
      data.forEach(function(d) {
        d.date = Date.parse(d.date);
        d.valueAtClose = +parseFloat(d.valueAtClose);
      });

      x.domain(d3.extent(data, function(d) { return d.date; }));
      y.domain(d3.extent(data, function(d) { return d.valueAtClose; }));

      svg.append("g")
         .attr("class", "x axis")
         .attr("transform", "translate(0," + height + ")")
         .call(xAxis);


      svg.append("g")
          .attr("class", "y axis axisLeft")
          .call(yAxis)
          .append("text")
          //.attr("transform", "rotate(-90)")
          .attr("transform", "translate(-50,-30)")
          .attr("y", 6)
          .attr("dy", ".71em")
          //.style("text-anchor", "end")
          .text("Nasdaq Index");


      svg.append("path")
          .datum(data)
          .attr("class", "line")
          .attr("d", line);
    });


    function type(d) {
      d.frequency = +d.frequency;
      return d;
    }
  </script>

  <div id='investment-desc'>
    <p>
    As we can see from the graph, there weren’t many investment before 1990, although the earliest collected data in crunch base's database was in 1984.
    </p>

    <p>
    From 1990 onwards, the investment increases as the stock market boom, which was accurately represented by the Nasdaq Indice. If we draw a scatter plot of Nasdaq indice against investment, we should see they lie along a long with positive slope, indicating a strong positive correlation.
    </p>

    <p>
    Since booming stock market creates lots of hot money and the financial booming gave investors a lot confidence, investors tended to invest more into high risk and high return companies like tech companies.
    </p>
  </div>
</div>

app/views/investment/show_unemployment.html.erb
<div id='investment'>
  <div id='investment-title'>
    US Unemployment Rate <span id='vs'>VS</span> Tech Company Investment Amount
  </div>
  <div id='investment-graph'></div>
  <script>
    var margin = {top: 30, right: 60, bottom: 30, left: 60},
        width = 960 - margin.left - margin.right,
        height = 500 - margin.top - margin.bottom;


    var x = d3.time.scale()
        .range([0, width-63]);
    var y = d3.scale.linear()
        .range([height, 0]);

    var x2 = d3.scale.ordinal()
        .rangeBands([0, width-63], .1);
    var y2 = d3.scale.linear()
        .range([height, 0]);

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom");
    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left");

    var x2Axis = d3.svg.axis()
        .scale(x)
        .orient("top");
    var yAxisRight = d3.svg.axis()
        .scale(y2)
        .orient("right")

    var line = d3.svg.line()
        .x(function(d) { return x(d.date); })
        .y(function(d) { return y(d.rate); });

    var svg = d3.select("#investment-graph").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
      .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");


    //bar graph for amount
    d3.tsv("/data/date_investmentAmount.tsv", type, function(error, data) {
      x2.domain(data.map(function(d) {
        return d.date; }));
      y2.domain([0, d3.max(data, function(d) {
        return parseFloat(d.amount); })]);

      svg.append("g")
          .attr("class", "y axis axisRight")
          .attr("transform", "translate(" + (width-62) + ",0)")
          .call(yAxisRight)
          .append("text")
          .attr("transform", "translate("+(110)+","+(-20)+")")
          .attr("y", 0)
          .attr("dy", ".71em")
          .style("text-anchor", "end")
          .text("Investment ($)");

    console.log(y2.domain());
      svg.selectAll(".bar")
          .data(data)
        .enter().append("rect")
          .attr("class", "bar")
          .attr("x", function(d) { return x2(d.date); })
          .attr("width", x2.rangeBand())
          .attr("y", function(d) { return y2(d.amount); })
          .attr("height", function(d) {
            return (height - y2(d.amount)); }

          );

    });

    // line graph for unemployment rate.
    d3.tsv("/data/unemploymentRate.tsv", function(error, data) {
      data.forEach(function(d) {
        console.log(d.date);
        d.date = Date.parse(d.date);
        console.log(d.date);
        d.rate = +(parseFloat(d.rate)/100.0);
        console.log(d.rate);
      });

      x.domain(d3.extent(data, function(d) {
        return d.date; }));
      y.domain(d3.extent(data, function(d) {
        return parseFloat(d.rate); }));

      svg.append("g")
          .attr("class", "x axis")
          .attr("transform", "translate(0," + height + ")")
          .call(xAxis);

      svg.append("g")
          .attr("class", "y axis axisLeft")
          .call(yAxis)
        .append("text")
          .attr("transform", "translate(-50,-30)")
          .attr("y", 6)
          .attr("dy", ".71em")
          //.style("text-anchor", "end")
          .text("Unemployment Rate");


      svg.append("path")
          .datum(data)
          .attr("class", "line")
          .attr("d", line);
    });


    function type(d) {
      d.frequency = +d.frequency;
      return d;
    }
  </script>

  <div id='investment-desc'>
    <p>
      As discussed in the Nasdaq Indice vs Investment graph, our analysis will focus on the non-trivial data part i.e. from 1990 onwards.
    </p>

    <p>
      During the following decade since then, unemployment rate was in a reverse correlation with investment.Because high unemployment rate shows the shortfall of economy, we could read from the graph that investors tended to make less risky investment into the hi-tech market during the recession around 2000.
    </p>

    <p>
      However, this metric of prediction investment trend was no longer a strong indication of investment  as since 2010 even though unemployment rate was relatively high, there were still large amount of investment flowed into hi-tech markets.
    </p>

    <p>
      One potential reason could be the unemployment is caused by technical revolution, which is positive related to the boom of technology investment.
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sequoia Number</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://d3js.org/d3.v3.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='title'>Sequoia Number</div>
<div id='navi'>
	<%= link_to 'Sequoia Number', sequoia_number_path %> |
	<%= link_to 'NASDAQ VS Investment', nasdaq_analysis_path %> |
	<%= link_to 'Unemployment VS Investment', unemployment_analysis_path %> |
	<%= link_to 'About', about_path %>
</div>
<div id='content'>
	<%= yield %>
</div>
</body>

<div id='push'></div>
<div id='footer'>
	Demo for CS194 - Data Science @ UC Berkeley |
	<a href="http://yanzhao.me">Yan Zhao</a>,
	<a href="http://www.linkedin.com/in/weijieclaireli">Weijie Li</a>
</div>
</html>

app/views/searches/sequoia_number.html.erb
<div id='sequoia'>
    <div id='sequoia-form'>
        <%= form_tag '/search_sequoia_number', method: 'get' do %>
          <p>
            What's the degree of separation between
            <%= text_field_tag :source %>
            and
            <%= text_field_tag :target, 'Sequoia Capital' %> ?
            <%= submit_tag "Tell me!", id: 'sequoia-form-submit' %>
          </p>
        <% end %>
    </div>

    <div id='sequoia-desc'>
        Please specify source and target.
    </div>

    <style>
    .link {
      stroke: #000;
      stroke-width: 1.5px;
    }
    .node text {
      pointer-events: none;
      font: 15px;
    }
    </style>

    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script>
    var width = 950,
        height = 500

    var svg = d3.select("#sequoia").append("svg")
        .attr("width", width)
        .attr("height", height);

    var force = d3.layout.force()
        .gravity(.05)
        .distance(250)
        .charge(-400)
        .size([width, height]);

    var drag = force.drag()
        .on("dragstart", dragstart);

    var data, link, node;

    $('form').submit(function(event){
        var form = $(this);

        $.ajax({
          type: form.attr('method'),
          url: form.attr('action'),
          data: form.serialize(),
          dataType: 'json',
          success: function(json, textStatus, jqXHR) {
            if (json.error) {
                $('#sequoia-desc').html(json.error);
                clean();
            } else {
                data = json;
                $('#sequoia-desc').html(json.degrees + ' degree of separation!');
                visualizeit();
            }
          }
        });

        event.preventDefault();
    });

    function clean() {
        $('line').remove();
        $('g').remove();
    }

    function visualizeit() {
        force
            .nodes(data.nodes)
            .links(data.links)
            .start();

        link = svg.selectAll(".link")
            .data(data.links)
        link.exit().remove();
        link.enter().append("line")
            .attr("class", "link");

        node = svg.selectAll(".node")
            .data(data.nodes)
        node.exit().remove();
        node.enter().append("g")
            .attr("class", "node")
            .on("dblclick", dblclick)
            .call(drag);

        $('g image').remove();
        node.append("image")
            .attr("xlink:href", function(d) {
                if (d.index%2==0) {
                    return "/assets/investor.png"
                } else {
                    return "/assets/company.jpg"
                }
            })
            .attr("x", -8)
            .attr("y", -8)
            .attr("width", 30)
            .attr("height", 30);

        $('g text').remove();
        node.append("text")
            .attr("dx", function(d) {
                if(d.target){
                    return -120;
                }else {
                    return 25;
                }
            })
            .attr("dy", function(d) {
                if(d.target){
                    return 10;
                }else {
                    return 0;
                }
            })
            .on('click', function(d){
                window.open(d.url, '_blank');
            })
            .text(function(d) { return d.name });

        force.on("tick", function() {
          link.attr("x1", function(d) { return d.source.x; })
              .attr("y1", function(d) { return d.source.y; })
              .attr("x2", function(d) { return d.target.x; })
              .attr("y2", function(d) { return d.target.y; });

          node.attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });
        });
    }


    function dblclick(d) {
        d.fixed = false;
    }

    function dragstart(d) {
        d.fixed = true;
    }
    </script>
</div>

app/views/sequoia/show.html.erb
<div id='sequoia'>
    <div id='sequoia-form'>
        <%= form_tag search_sequoia_number_path, method: 'get' do %>
          <p>
            What's the degree of separation between
            <%= text_field_tag :source, nil, data: {autocomplete_source: search_auto_complete_path} %>
            and
            <%= text_field_tag :target, 'Sequoia Capital', data: {autocomplete_source: search_auto_complete_path} %> ?
            <%= submit_tag "Tell me!", id: 'sequoia-form-submit' %>
          </p>
        <% end %>
    </div>

    <div id='sequoia-result'>
        Please specify source and target.
    </div>

    <div id='sequoia-graph'>
        <style>
            .link {
              stroke: #000;
              stroke-width: 1.5px;
            }
            .node text {
              pointer-events: none;
              font: 15px;
            }
        </style>
        <script>
            var width = 950,
                height = 500,
                distance = 700

            var svg = d3.select("#sequoia-graph").append("svg")
                .attr("width", width)
                .attr("height", height);

            var force = d3.layout.force()
                .gravity(.05)
                .charge(-400)
                .size([width, height]);

            var drag = force.drag()
                .on("dragstart", dragstart);

            var data, link, node;

            $('form').submit(function(event){
                var form = $(this);

                $.ajax({
                  type: form.attr('method'),
                  url: form.attr('action'),
                  data: form.serialize(),
                  dataType: 'json',
                  success: function(json, textStatus, jqXHR) {
                    if (json.error) {
                        $('#sequoia-result').html(json.error);
                        clean();
                    } else {
                        data = json;
                        $('#sequoia-result').html(json.degrees + ' degree of separation!');
                        visualizeit();
                    }
                  }
                });

                event.preventDefault();
            });

            function clean() {
                $('line').remove();
                $('g').remove();
            }

            function visualizeit() {
                force
                    .distance(distance/(data.degrees*2))
                    .nodes(data.nodes)
                    .links(data.links)
                    .start();

                link = svg.selectAll(".link")
                    .data(data.links)
                link.exit().remove();
                link.enter().append("line")
                    .attr("class", "link");

                node = svg.selectAll(".node")
                    .data(data.nodes)
                node.exit().remove();
                node.enter().append("g")
                    .attr("class", "node")
                    .on("dblclick", dblclick)
                    .call(drag);

                $('g image').remove();
                node.append("image")
                    .attr("xlink:href", function(d) {
                        if (d.index%2==0) {
                            return "/assets/investor.png"
                        } else {
                            return "/assets/company.png"
                        }
                    })
                    .attr("x", -8)
                    .attr("y", -8)
                    .attr("width", 30)
                    .attr("height", 30);

                $('g text').remove();
                node.append("text")
                    .attr("dx", function(d) {
                        if(d.target){
                            return -50;
                        }else {
                            return 25;
                        }
                    })
                    .attr("dy", function(d) {
                        if(d.target){
                            return 40;
                        }else {
                            return 0;
                        }
                    })
                    .text(function(d) { return d.name });

                $('g text').on('click', function(d){
                    alert('haha');
                    window.open(d.url, '_blank');
                });

                force.on("tick", function() {
                  link.attr("x1", function(d) { return d.source.x; })
                      .attr("y1", function(d) { return d.source.y; })
                      .attr("x2", function(d) { return d.target.x; })
                      .attr("y2", function(d) { return d.target.y; });

                  node.attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });
                });
            }


            function dblclick(d) {
                d.fixed = false;
            }

            function dragstart(d) {
                d.fixed = true;
            }
        </script>
    </div>

    <div id='sequoia-desc'>
        <p style='text-align: center;'>
            This is the fun part!
        </p>

        <p>
            The idea of <b>Sequoia Number</b> comes from <b>Erdős Number</b>. Erdős Number means the distance to
            the famous mathematicians with each hop of co-authorship as one distance unit.
        </p>

        <p>
            We followed the same rule to calculate the distance between two investing companies with each hop as two companies
            have invested in the same company.
        </p>

        <p>
            Specifically, we would like to see investing company's distance to Sequoia Capital due to its famous history and all
            the great technology companies it has invested.
        </p>

        <p>
            We have calculated the distance between each investment company to Sequoia Capital, and the average distance is <b>1.776</b>.
        </p>
    </div>
</div>

app/views/statics/about.html.erb
<h2>Who are we</h2>
<div class='about-content'>
	We are <a href="http://yanzhao.me">Yan Zhao</a> and <a href="http://www.linkedin.com/in/weijieclaireli">Weijie Li</a>, group <b>Unicode</b> from CS194 Data Science @ UC Berkely. This is a demo for our final project.
</div>

<h2>Overview</h2>
<div class='about-content'>
	<p>
		Not really a problem, but fun facts we are trying to discover.
	</p>

	<p>
		Sequoia Capital is a well known technology venture company, and companies like Whatsapp, Google, Apple, Facebook and many other big name companies have received venture from Sequoia.
	</p>

	<p>
		We are curious in the pattern of Sequoia’s investment activities, and more generalized, we would like to probe how technology investment activities are related to U.S. economy.
	</p>

	<p>
		Thus, we created this product, dynamic Sequoia Number query and analysis of technology investment and US Economy.
	</p>
</div>

<h2>Related System</h2>
<div class='about-content'>
	<p>
		Not really. The most similar system we could find is <b>Six Degree of Kevin Bacon</b> and <b>Erdős Number</b> project. But they are about
		mathmatician and hollywood celebrities, not investing companies.
	</p>
</div>

<h2>Tools</h2>
<div class='about-content'>
	<p>
		We have used several tools for our product.
	</p>
	<p>
		For the data cleanning process, we have used <b>OpenRefine</b>. We have used <b>Neo4j</b> graph database to achieve real time graph traversal
		in order to query shortest path between two investment compnaies. As for the demonstration, we have used <b>Ruby on Rails</b> to build this
		interactive demo. Last but not least, we have <b>D3js</b> as our visualization tools which works fantastically.
	</p>
</div>

<h2>Data Sets</h2>
<div class='about-content'>
	<p>
		We have used three data sets total.
	</p>
	<p>
		The major one is <a href="http://info.crunchbase.com/about/crunchbase-data-exports/">investment activity data sets from crunchbase</a>. This database is a schema oriented datasets that stores in a Excel file. The size of this data sets is almost 100 thousand records.
	</p>
	<p>
		The <b>Nasdaq indice</b> is from Yahoo Finance. We collected the value at close by day and calculated the average value by month since 1984. The data set consistes about seven thousands records.
	</p>
	<p>
		The <b>unemployment rate</b> data set is from Bureau of Labor Statistics. It consists of 240 which indicates the unemployment rate for each month sicne since 1984.
	</p>
</div>

<h2>Data Product</h2>
<div class='about-content'>
	<p>
		Our product is a Software as a Service to let people interactively query the <b>investing distance</b> between two venture company.
	</p>

	<p>
		Also, we have added two static analysis about investing activity vs nasdaq indices and US unemployment rate, respectively.
	</p>
</div>

<h2>Challenge</h2>
<div class='about-content'>
	<p>
		One major problem we have encountered is in cleaning up the data due to the precense of Unicode, we end up configure our database to allow
		Unicode storage, which works quite well.
	</p>

	<p>
		Another problem would be finding an graph database services to store our data online is not very cheap, so we decide demo the app locally.
	</p>
</div>

<h2>Future Work</h2>
<div class='about-content'>
	<p>
		Hosting our app online so more people can play with it!
	</p>

	<p>
		Also, we are very interested in the relationship between a investing company's valuation and its Sequoia Number. This is something we would
		like to investigate.
	</p>
</div>